<a href="https://colab.research.google.com/github/dianakang/DIANA_Pytorch/blob/master/%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%9E%85%EB%AC%B8_%ED%95%84%EC%88%98%EC%98%81%EC%83%81(%ED%85%90%EC%84%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

유튜버 딥러닝호형님의 영상을 참고했습니다.

(출처: https://www.youtube.com/watch?v=6SF_qAd99Yg&t=8s)



---

Pytorch는 내부적인 CUDA API를 통해 GPU연산을 제공한다.


# 1강. Tensor

torch의 tensor는 numpy array와 사용법이 유사하다.

In [1]:
import torch
import numpy as np

## 1.1. torch메서드 확인

In [2]:
x = torch.empty(5,4)
print(x)

tensor([[2.0418e-35, 0.0000e+00, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
        [7.0065e-44, 7.0065e-44, 1.1771e-43, 6.8664e-44],
        [7.1466e-44, 8.1275e-44, 7.2868e-44, 7.4269e-44],
        [8.1275e-44, 7.2868e-44, 6.8664e-44, 6.4460e-44]])


In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(5,6)  # random

tensor([[0.8106, 0.5441, 0.2365, 0.1520, 0.5990, 0.4463],
        [0.5734, 0.2506, 0.1277, 0.5957, 0.7487, 0.3552],
        [0.8942, 0.7181, 0.9107, 0.2778, 0.2304, 0.1866],
        [0.9693, 0.4437, 0.6644, 0.2000, 0.3753, 0.8154],
        [0.7494, 0.4851, 0.4697, 0.2374, 0.5311, 0.6825]])

In [6]:
l = [13,4]
r = np.array([4,56,7])

## 1.2. numpy -> tensor로 변환

파이토치의 기본단위는 텐서이기 때문에 위와 같이 데이터가 list나 array로 되어있을 경우, 텐서로 먼저 변환시켜야함.

In [7]:
# tensor로 변환
torch.tensor(l)

tensor([13,  4])

In [8]:
# tensor로 변환
torch.tensor(r)

tensor([ 4, 56,  7])

In [9]:
# 사이즈 확인
x.size()

torch.Size([5, 4])

In [10]:
# 타입 확인
type(x)

torch.Tensor

In [11]:
# 랜덤 텐서 생성
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.1006, 0.7239],
        [0.4751, 0.0374]])
tensor([[0.1539, 0.3906],
        [0.3814, 0.6929]])


In [12]:
# 기본 연산
x + y

tensor([[0.2545, 1.1145],
        [0.8565, 0.7303]])

In [13]:
# torch.add()메서드 사용 연산
torch.add(x,y)

tensor([[0.2545, 1.1145],
        [0.8565, 0.7303]])

In [14]:
y.add(x)  # y에 x를 더한다는 의미

tensor([[0.2545, 1.1145],
        [0.8565, 0.7303]])

In [15]:
# y에 x를 더해서 y를 대체
y.add_(x)  # _는 inplace방식 -> 변수를 대체할 때 사용 

tensor([[0.2545, 1.1145],
        [0.8565, 0.7303]])

In [16]:
# 1행 1열 출력 -> 파이썬에서는 numbering이 0부터 시작한다는 점 잊지않기!
y[1,1] 

tensor(0.7303)

In [17]:
# 1열 출력
y[:,1]

tensor([1.1145, 0.7303])

In [18]:
x = torch.rand(8,8)
print(x)

tensor([[0.3282, 0.7743, 0.2463, 0.8499, 0.4510, 0.5600, 0.8783, 0.3684],
        [0.0285, 0.2635, 0.8370, 0.7187, 0.8084, 0.3509, 0.5492, 0.8664],
        [0.9391, 0.9621, 0.8409, 0.5726, 0.0091, 0.6265, 0.3203, 0.0957],
        [0.8288, 0.1299, 0.4630, 0.6450, 0.6285, 0.0416, 0.1256, 0.2919],
        [0.4112, 0.2209, 0.9879, 0.4961, 0.9679, 0.7821, 0.4833, 0.5200],
        [0.6848, 0.8019, 0.4120, 0.1674, 0.7137, 0.8916, 0.3186, 0.7193],
        [0.8236, 0.4301, 0.4722, 0.3166, 0.1359, 0.4745, 0.3827, 0.8811],
        [0.8258, 0.0684, 0.8431, 0.0508, 0.3629, 0.8167, 0.2033, 0.5721]])


In [19]:
# 사이즈 변환 - .view() => 열 기준으로 나열 메서드
x.view(64)   ## 64를 쓰는 이유 = 8*8이므로

tensor([0.3282, 0.7743, 0.2463, 0.8499, 0.4510, 0.5600, 0.8783, 0.3684, 0.0285,
        0.2635, 0.8370, 0.7187, 0.8084, 0.3509, 0.5492, 0.8664, 0.9391, 0.9621,
        0.8409, 0.5726, 0.0091, 0.6265, 0.3203, 0.0957, 0.8288, 0.1299, 0.4630,
        0.6450, 0.6285, 0.0416, 0.1256, 0.2919, 0.4112, 0.2209, 0.9879, 0.4961,
        0.9679, 0.7821, 0.4833, 0.5200, 0.6848, 0.8019, 0.4120, 0.1674, 0.7137,
        0.8916, 0.3186, 0.7193, 0.8236, 0.4301, 0.4722, 0.3166, 0.1359, 0.4745,
        0.3827, 0.8811, 0.8258, 0.0684, 0.8431, 0.0508, 0.3629, 0.8167, 0.2033,
        0.5721])

.view()메서드는 CNN에서 컨볼루션 레이어를 연산하다가 마지막단의 fully connected layer를 들어갈 때 정사각형 이미지를 1열로 쭈욱 펴주잖아요. 그때 사용합니다.

In [20]:
x.view(4,16)  # 이렇게 64의 약수 아무거나 넣어서도 변환이 가능하다.

tensor([[0.3282, 0.7743, 0.2463, 0.8499, 0.4510, 0.5600, 0.8783, 0.3684, 0.0285,
         0.2635, 0.8370, 0.7187, 0.8084, 0.3509, 0.5492, 0.8664],
        [0.9391, 0.9621, 0.8409, 0.5726, 0.0091, 0.6265, 0.3203, 0.0957, 0.8288,
         0.1299, 0.4630, 0.6450, 0.6285, 0.0416, 0.1256, 0.2919],
        [0.4112, 0.2209, 0.9879, 0.4961, 0.9679, 0.7821, 0.4833, 0.5200, 0.6848,
         0.8019, 0.4120, 0.1674, 0.7137, 0.8916, 0.3186, 0.7193],
        [0.8236, 0.4301, 0.4722, 0.3166, 0.1359, 0.4745, 0.3827, 0.8811, 0.8258,
         0.0684, 0.8431, 0.0508, 0.3629, 0.8167, 0.2033, 0.5721]])

위의 4,16은 64의 약수를 계산해서 넣은 것이지만, 우리는 매번 약수를 이렇게 일일이 계산할 수 없다. 

이를 해결하기 위해 한쪽에 -1를 넣어 자동으로 약수를 계산하게 해준다.

In [21]:
x.view(-1,16)  

tensor([[0.3282, 0.7743, 0.2463, 0.8499, 0.4510, 0.5600, 0.8783, 0.3684, 0.0285,
         0.2635, 0.8370, 0.7187, 0.8084, 0.3509, 0.5492, 0.8664],
        [0.9391, 0.9621, 0.8409, 0.5726, 0.0091, 0.6265, 0.3203, 0.0957, 0.8288,
         0.1299, 0.4630, 0.6450, 0.6285, 0.0416, 0.1256, 0.2919],
        [0.4112, 0.2209, 0.9879, 0.4961, 0.9679, 0.7821, 0.4833, 0.5200, 0.6848,
         0.8019, 0.4120, 0.1674, 0.7137, 0.8916, 0.3186, 0.7193],
        [0.8236, 0.4301, 0.4722, 0.3166, 0.1359, 0.4745, 0.3827, 0.8811, 0.8258,
         0.0684, 0.8431, 0.0508, 0.3629, 0.8167, 0.2033, 0.5721]])

이러한 원리로 x.view(4,16)와 x.view(-1,16)의 출력값이 같다는 것을 알 수 있다. 

## 1.3. tensor -> numpy로 변환

In [22]:
# .numpy()메서드 이용
y = x.numpy()
print(y)

[[0.32818234 0.77433616 0.24625474 0.8499495  0.45101953 0.55997366
  0.87831235 0.36835295]
 [0.02845269 0.263494   0.8369749  0.7186853  0.80841684 0.3509233
  0.5491844  0.8664115 ]
 [0.9391174  0.9620616  0.84094906 0.57257646 0.00911766 0.6265306
  0.32031518 0.09565753]
 [0.82883364 0.12988353 0.46300292 0.645043   0.6284919  0.04161167
  0.1255855  0.2918632 ]
 [0.41124427 0.2209199  0.98793644 0.49605006 0.96788305 0.7821419
  0.48333323 0.5199512 ]
 [0.68476146 0.8018887  0.41197258 0.16741848 0.7137304  0.89159894
  0.31860155 0.71930027]
 [0.8235764  0.43009847 0.47222966 0.31664097 0.13588858 0.4744838
  0.38265115 0.8810694 ]
 [0.82581145 0.06841761 0.84313214 0.0508126  0.36291492 0.81671613
  0.20325536 0.5720675 ]]


In [23]:
type(y)

numpy.ndarray

In [24]:
x = torch.ones(1)
x

tensor([1.])

위의 tensor안의 값을 정수나 실수와 같은 숫자 형태로 불러오고 싶을 때 item을 사용.

이는 텐서가 skala일 때, 즉 원소가 한 개일때만 사용이 가능함.

주로 loss값을 직접 뽑아내고 싶을 때 많이 사용한다.

In [25]:
x.item() # 숫자만 뽑아오기

1.0